// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Query.Analysis.Buckling.LoadFactors;
using SpaceGassApi.Job.Query.Analysis.Buckling.Member;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Query.Analysis.Buckling
{
    /// <summary>
    /// Builds and executes requests for operations under \job\query\analysis\buckling
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BucklingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The loadFactors property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Buckling.LoadFactors.LoadFactorsRequestBuilder LoadFactors
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Buckling.LoadFactors.LoadFactorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The member property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Buckling.Member.MemberRequestBuilder Member
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Buckling.Member.MemberRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.Buckling.BucklingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BucklingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis/buckling", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.Buckling.BucklingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BucklingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis/buckling", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
