// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SpaceGassApi.Job.Structure.Plates.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \job\structure\plates\bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/structure/plates/bulk{?continueOnError*,keys*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/structure/plates/bulk{?continueOnError*,keys*}", rawUrl)
        {
        }
        /// <summary>
        /// Delete Bulk
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.ObjectBatchResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SpaceGassApi.Models.ObjectBatchResult?> DeleteAsync(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SpaceGassApi.Models.ObjectBatchResult> DeleteAsync(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SpaceGassApi.Models.ObjectBatchResult>(requestInfo, global::SpaceGassApi.Models.ObjectBatchResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates multiple items in a bulk operation.Each item must include its Key in the request body.If a validator is registered, all items are validated upfront before any are updated.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.PlateBatchResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SpaceGassApi.Models.PlateBatchResult?> PatchAsync(List<global::SpaceGassApi.Models.PlateUpdate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SpaceGassApi.Models.PlateBatchResult> PatchAsync(List<global::SpaceGassApi.Models.PlateUpdate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SpaceGassApi.Models.PlateBatchResult>(requestInfo, global::SpaceGassApi.Models.PlateBatchResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates multiple items in a bulk operation.If a validator is registered, all items are validated upfront before any are created.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.PlateBatchResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SpaceGassApi.Models.PlateBatchResult?> PostAsync(List<global::SpaceGassApi.Models.PlateCreate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SpaceGassApi.Models.PlateBatchResult> PostAsync(List<global::SpaceGassApi.Models.PlateCreate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SpaceGassApi.Models.PlateBatchResult>(requestInfo, global::SpaceGassApi.Models.PlateBatchResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete Bulk
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates multiple items in a bulk operation.Each item must include its Key in the request body.If a validator is registered, all items are validated upfront before any are updated.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(List<global::SpaceGassApi.Models.PlateUpdate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(List<global::SpaceGassApi.Models.PlateUpdate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Creates multiple items in a bulk operation.If a validator is registered, all items are validated upfront before any are created.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(List<global::SpaceGassApi.Models.PlateCreate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(List<global::SpaceGassApi.Models.PlateCreate> body, Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Delete Bulk
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Whether to continue on error</summary>
            [QueryParameter("continueOnError")]
            public bool? ContinueOnError { get; set; }
            /// <summary>Array of entity keys to delete (e.g., ?keys=1&amp;keys=2&amp;keys=3)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("keys")]
            public int?[]? Keys { get; set; }
#nullable restore
#else
            [QueryParameter("keys")]
            public int?[] Keys { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderDeleteQueryParameters>
        {
        }
        /// <summary>
        /// Updates multiple items in a bulk operation.Each item must include its Key in the request body.If a validator is registered, all items are validated upfront before any are updated.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderPatchQueryParameters 
        {
            /// <summary>Whether to continue processing after individual failures</summary>
            [QueryParameter("continueOnError")]
            public bool? ContinueOnError { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderPatchRequestConfiguration : RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPatchQueryParameters>
        {
        }
        /// <summary>
        /// Creates multiple items in a bulk operation.If a validator is registered, all items are validated upfront before any are created.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderPostQueryParameters 
        {
            /// <summary>Whether to continue processing after individual failures</summary>
            [QueryParameter("continueOnError")]
            public bool? ContinueOnError { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BulkRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SpaceGassApi.Job.Structure.Plates.Bulk.BulkRequestBuilder.BulkRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
