// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Log level for analysis messages</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AnalysisLogLevel
    {
        [EnumMember(Value = "Info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "Error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
