// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Live progress data from the analysis solver.Captured via Windows messages from SGSolver.EXE to the display proxy window.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnalysisProgress : IParsable
    {
        /// <summary>Current step being processed (0-based index)</summary>
        public int? CurrentStep { get; set; }
        /// <summary>Iteration progress percentage (0-100) for the current solver iteration</summary>
        public int? IterationPercentage { get; set; }
        /// <summary>Load case progress information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceGassApi.Models.AnalysisLoadCaseProgress? LoadCaseCount { get; set; }
#nullable restore
#else
        public global::SpaceGassApi.Models.AnalysisLoadCaseProgress LoadCaseCount { get; set; }
#endif
        /// <summary>Live load case status string, updated as load cases are processed.e.g., starts as &quot;55&quot; then becomes &quot;40 (29/55)&quot; during analysis.Null if no load case information is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoadCaseStatus { get; set; }
#nullable restore
#else
        public string LoadCaseStatus { get; set; }
#endif
        /// <summary>Log messages from the solver (info, warnings, errors).Includes error/warning messages (from negative textIndex) and completion info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceGassApi.Models.AnalysisLogMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::SpaceGassApi.Models.AnalysisLogMessage> Messages { get; set; }
#endif
        /// <summary>Current status text from the solver (e.g., &quot;Analysing..&quot;, &quot;Saving results..&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusText { get; set; }
#nullable restore
#else
        public string StatusText { get; set; }
#endif
        /// <summary>Per-step labels/names (e.g., &quot;Assembling geometric data&quot;, &quot;Solving stiffness matrix&quot;).Array index corresponds to step index. Null entries mean no label received yet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StepLabels { get; set; }
#nullable restore
#else
        public List<string> StepLabels { get; set; }
#endif
        /// <summary>Per-step percentage completion. Array index corresponds to step index.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? StepPercentages { get; set; }
#nullable restore
#else
        public List<int?> StepPercentages { get; set; }
#endif
        /// <summary>Total number of analysis steps/phases discovered so far.Inferred dynamically from solver messages (the solver does not declare total steps upfront).</summary>
        public int? TotalSteps { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.AnalysisProgress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.AnalysisProgress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.AnalysisProgress();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentStep", n => { CurrentStep = n.GetIntValue(); } },
                { "iterationPercentage", n => { IterationPercentage = n.GetIntValue(); } },
                { "loadCaseCount", n => { LoadCaseCount = n.GetObjectValue<global::SpaceGassApi.Models.AnalysisLoadCaseProgress>(global::SpaceGassApi.Models.AnalysisLoadCaseProgress.CreateFromDiscriminatorValue); } },
                { "loadCaseStatus", n => { LoadCaseStatus = n.GetStringValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::SpaceGassApi.Models.AnalysisLogMessage>(global::SpaceGassApi.Models.AnalysisLogMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "statusText", n => { StatusText = n.GetStringValue(); } },
                { "stepLabels", n => { StepLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "stepPercentages", n => { StepPercentages = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "totalSteps", n => { TotalSteps = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentStep", CurrentStep);
            writer.WriteIntValue("iterationPercentage", IterationPercentage);
            writer.WriteObjectValue<global::SpaceGassApi.Models.AnalysisLoadCaseProgress>("loadCaseCount", LoadCaseCount);
            writer.WriteStringValue("loadCaseStatus", LoadCaseStatus);
            writer.WriteCollectionOfObjectValues<global::SpaceGassApi.Models.AnalysisLogMessage>("messages", Messages);
            writer.WriteStringValue("statusText", StatusText);
            writer.WriteCollectionOfPrimitiveValues<string>("stepLabels", StepLabels);
            writer.WriteCollectionOfPrimitiveValues<int?>("stepPercentages", StepPercentages);
            writer.WriteIntValue("totalSteps", TotalSteps);
        }
    }
}
#pragma warning restore CS0618
