// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Eigensolver theory used for buckling analysis.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BucklingTheory
    {
        [EnumMember(Value = "SigncountEigensolver")]
        #pragma warning disable CS1591
        SigncountEigensolver,
        #pragma warning restore CS1591
        [EnumMember(Value = "ClassicEigensolver")]
        #pragma warning disable CS1591
        ClassicEigensolver,
        #pragma warning restore CS1591
    }
}
