// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Settings DTO for Dynamic Frequency Analysis.Properties map to the SPACEGASS NetSGFrequency struct.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicFrequencySettings : IParsable
    {
        /// <summary>Whether to check for non-existent load cases referenced in the analysis.When true, warnings are generated for missing load cases.</summary>
        public bool? CheckNonExistentCases { get; set; }
        /// <summary>Drilling stiffness multiplier for plate elements.</summary>
        public float? DrillingStiffness { get; set; }
        /// <summary>Whether to perform extra iterations for improved mode shape accuracy.</summary>
        public bool? ExtraIterations { get; set; }
        /// <summary>Frequency shift value for the eigensolver.</summary>
        public float? FrequencyShift { get; set; }
        /// <summary>Load cases to include in the analysis.Use &quot;all&quot; or &quot;&quot; to include all load cases (default).Use a comma-separated list of numbers and ranges (e.g., &quot;1,3,5-10&quot;).Maximum 50 entries (individual numbers and ranges each count as entries).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoadCases { get; set; }
#nullable restore
#else
        public string LoadCases { get; set; }
#endif
        /// <summary>Lower limit for the frequency range.</summary>
        public float? LowerLimit { get; set; }
        /// <summary>Number of dynamic modes to compute.</summary>
        public int? Modes { get; set; }
        /// <summary>Axis used for optimization in analysis.</summary>
        public global::SpaceGassApi.Models.OptimizationAxis? OptimizationAxis { get; set; }
        /// <summary>Optimization method for Dynamic Frequency analysis.Note: These have different integer mappings than the static/buckling OptimizationMethod enum.</summary>
        public global::SpaceGassApi.Models.FrequencyOptimizationMethod? OptimizationMethod { get; set; }
        /// <summary>X coordinate for optimization.</summary>
        public float? OptimizationX { get; set; }
        /// <summary>Y coordinate for optimization.</summary>
        public float? OptimizationY { get; set; }
        /// <summary>Z coordinate for optimization.</summary>
        public float? OptimizationZ { get; set; }
        /// <summary>Plate element formulation type.</summary>
        public global::SpaceGassApi.Models.PlateType? PlateType { get; set; }
        /// <summary>Whether to retain results of other load cases during analysis.When true, results from previously analysed load cases are preserved.</summary>
        public bool? RetainCases { get; set; }
        /// <summary>Matrix solver type used by the analysis engine.</summary>
        public global::SpaceGassApi.Models.SolverType? SolverType { get; set; }
        /// <summary>Whether to stabilize unrestrained nodes during analysis.When true, temporary restraints are added to prevent instability.</summary>
        public bool? StabilizeUnrestrainedNodes { get; set; }
        /// <summary>Convergence tolerance for the frequency analysis.</summary>
        public float? Tolerance { get; set; }
        /// <summary>Upper limit for the frequency range.</summary>
        public float? UpperLimit { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.DynamicFrequencySettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.DynamicFrequencySettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.DynamicFrequencySettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checkNonExistentCases", n => { CheckNonExistentCases = n.GetBoolValue(); } },
                { "drillingStiffness", n => { DrillingStiffness = n.GetFloatValue(); } },
                { "extraIterations", n => { ExtraIterations = n.GetBoolValue(); } },
                { "frequencyShift", n => { FrequencyShift = n.GetFloatValue(); } },
                { "loadCases", n => { LoadCases = n.GetStringValue(); } },
                { "lowerLimit", n => { LowerLimit = n.GetFloatValue(); } },
                { "modes", n => { Modes = n.GetIntValue(); } },
                { "optimizationAxis", n => { OptimizationAxis = n.GetEnumValue<global::SpaceGassApi.Models.OptimizationAxis>(); } },
                { "optimizationMethod", n => { OptimizationMethod = n.GetEnumValue<global::SpaceGassApi.Models.FrequencyOptimizationMethod>(); } },
                { "optimizationX", n => { OptimizationX = n.GetFloatValue(); } },
                { "optimizationY", n => { OptimizationY = n.GetFloatValue(); } },
                { "optimizationZ", n => { OptimizationZ = n.GetFloatValue(); } },
                { "plateType", n => { PlateType = n.GetEnumValue<global::SpaceGassApi.Models.PlateType>(); } },
                { "retainCases", n => { RetainCases = n.GetBoolValue(); } },
                { "solverType", n => { SolverType = n.GetEnumValue<global::SpaceGassApi.Models.SolverType>(); } },
                { "stabilizeUnrestrainedNodes", n => { StabilizeUnrestrainedNodes = n.GetBoolValue(); } },
                { "tolerance", n => { Tolerance = n.GetFloatValue(); } },
                { "upperLimit", n => { UpperLimit = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("checkNonExistentCases", CheckNonExistentCases);
            writer.WriteFloatValue("drillingStiffness", DrillingStiffness);
            writer.WriteBoolValue("extraIterations", ExtraIterations);
            writer.WriteFloatValue("frequencyShift", FrequencyShift);
            writer.WriteStringValue("loadCases", LoadCases);
            writer.WriteFloatValue("lowerLimit", LowerLimit);
            writer.WriteIntValue("modes", Modes);
            writer.WriteEnumValue<global::SpaceGassApi.Models.OptimizationAxis>("optimizationAxis", OptimizationAxis);
            writer.WriteEnumValue<global::SpaceGassApi.Models.FrequencyOptimizationMethod>("optimizationMethod", OptimizationMethod);
            writer.WriteFloatValue("optimizationX", OptimizationX);
            writer.WriteFloatValue("optimizationY", OptimizationY);
            writer.WriteFloatValue("optimizationZ", OptimizationZ);
            writer.WriteEnumValue<global::SpaceGassApi.Models.PlateType>("plateType", PlateType);
            writer.WriteBoolValue("retainCases", RetainCases);
            writer.WriteEnumValue<global::SpaceGassApi.Models.SolverType>("solverType", SolverType);
            writer.WriteBoolValue("stabilizeUnrestrainedNodes", StabilizeUnrestrainedNodes);
            writer.WriteFloatValue("tolerance", Tolerance);
            writer.WriteFloatValue("upperLimit", UpperLimit);
        }
    }
}
#pragma warning restore CS0618
