// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Generic metadata for any entity type.Provides schema information for clients to validate and display entity data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityMetadata : IParsable
    {
        /// <summary>Current count of entities</summary>
        public int? Count { get; set; }
        /// <summary>Human-readable display name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Field definitions describing the entity&apos;s schema.Populated from the SPACE GASS DataSpecification.Null if field metadata is not available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceGassApi.Models.FieldMetadata>? Fields { get; set; }
#nullable restore
#else
        public List<global::SpaceGassApi.Models.FieldMetadata> Fields { get; set; }
#endif
        /// <summary>Whether this entity has a GUID field</summary>
        public bool? HasGuidField { get; set; }
        /// <summary>Identifies entity types managed by the API.Kept separate from SGFileID to allow for future API-only entitiesthat may not have a formal SPACE GASS FileID.</summary>
        public global::SpaceGassApi.Models.EntityId? Id { get; set; }
        /// <summary>Maximum key currently in use (for single-int key entities only)</summary>
        public int? MaxKey { get; set; }
        /// <summary>Next available key (for single-int key entities only)</summary>
        public int? NextKey { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.EntityMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.EntityMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.EntityMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "count", n => { Count = n.GetIntValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::SpaceGassApi.Models.FieldMetadata>(global::SpaceGassApi.Models.FieldMetadata.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hasGuidField", n => { HasGuidField = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetEnumValue<global::SpaceGassApi.Models.EntityId>(); } },
                { "maxKey", n => { MaxKey = n.GetIntValue(); } },
                { "nextKey", n => { NextKey = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteCollectionOfObjectValues<global::SpaceGassApi.Models.FieldMetadata>("fields", Fields);
            writer.WriteBoolValue("hasGuidField", HasGuidField);
            writer.WriteEnumValue<global::SpaceGassApi.Models.EntityId>("id", Id);
            writer.WriteIntValue("maxKey", MaxKey);
            writer.WriteIntValue("nextKey", NextKey);
        }
    }
}
#pragma warning restore CS0618
