// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Metadata for a single field in an entity table.Provides schema information for clients to validate and display entity data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FieldMetadata : IParsable
    {
        /// <summary>Whether the field can be empty/null</summary>
        public bool? AllowEmpty { get; set; }
        /// <summary>Data type (Integer, Double, String, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataType { get; set; }
#nullable restore
#else
        public string DataType { get; set; }
#endif
        /// <summary>Default value (if applicable)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Default { get; set; }
#nullable restore
#else
        public string Default { get; set; }
#endif
        /// <summary>Field name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>Field index in the underlying data structure</summary>
        public int? Index { get; set; }
        /// <summary>Maximum allowed value (if applicable)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Max { get; set; }
#nullable restore
#else
        public string Max { get; set; }
#endif
        /// <summary>Minimum allowed value (if applicable)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Min { get; set; }
#nullable restore
#else
        public string Min { get; set; }
#endif
        /// <summary>Resolved unit label based on current job units (e.g., &quot;mm&quot;, &quot;kN/mm&quot;).This is what values in requests/responses are measured in.Null if the field has no units.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Units { get; set; }
#nullable restore
#else
        public string Units { get; set; }
#endif
        /// <summary>Units mask token (e.g., &quot;&lt;Length&gt;&quot;) - null if no units.This is the raw mask from the DataSpec.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitsMask { get; set; }
#nullable restore
#else
        public string UnitsMask { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.FieldMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.FieldMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.FieldMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowEmpty", n => { AllowEmpty = n.GetBoolValue(); } },
                { "dataType", n => { DataType = n.GetStringValue(); } },
                { "default", n => { Default = n.GetStringValue(); } },
                { "fieldName", n => { FieldName = n.GetStringValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "max", n => { Max = n.GetStringValue(); } },
                { "min", n => { Min = n.GetStringValue(); } },
                { "units", n => { Units = n.GetStringValue(); } },
                { "unitsMask", n => { UnitsMask = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowEmpty", AllowEmpty);
            writer.WriteStringValue("dataType", DataType);
            writer.WriteStringValue("default", Default);
            writer.WriteStringValue("fieldName", FieldName);
            writer.WriteIntValue("index", Index);
            writer.WriteStringValue("max", Max);
            writer.WriteStringValue("min", Min);
            writer.WriteStringValue("units", Units);
            writer.WriteStringValue("unitsMask", UnitsMask);
        }
    }
}
#pragma warning restore CS0618
