// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Optimization method for Dynamic Frequency analysis.Note: These have different integer mappings than the static/buckling OptimizationMethod enum.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FrequencyOptimizationMethod
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "General")]
        #pragma warning disable CS1591
        General,
        #pragma warning restore CS1591
        [EnumMember(Value = "Linear")]
        #pragma warning disable CS1591
        Linear,
        #pragma warning restore CS1591
        [EnumMember(Value = "Angular")]
        #pragma warning disable CS1591
        Angular,
        #pragma warning restore CS1591
    }
}
