// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Friction normal axis for restraint friction definitions.Maps to SPACE GASS lookup table &quot;N/X/Y/Z Axes&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FrictionNormalAxis
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "XAxis")]
        #pragma warning disable CS1591
        XAxis,
        #pragma warning restore CS1591
        [EnumMember(Value = "YAxis")]
        #pragma warning disable CS1591
        YAxis,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZAxis")]
        #pragma warning disable CS1591
        ZAxis,
        #pragma warning restore CS1591
    }
}
