// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Mass Density unit types (Field Index 3)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MassDensityUnit
    {
        [EnumMember(Value = "KipsPerCubicFoot")]
        #pragma warning disable CS1591
        KipsPerCubicFoot,
        #pragma warning restore CS1591
        [EnumMember(Value = "KipsPerCubicInch")]
        #pragma warning disable CS1591
        KipsPerCubicInch,
        #pragma warning restore CS1591
        [EnumMember(Value = "PoundsPerCubicFoot")]
        #pragma warning disable CS1591
        PoundsPerCubicFoot,
        #pragma warning restore CS1591
        [EnumMember(Value = "PoundsPerCubicInch")]
        #pragma warning disable CS1591
        PoundsPerCubicInch,
        #pragma warning restore CS1591
        [EnumMember(Value = "TonnesPerCubicMetre")]
        #pragma warning disable CS1591
        TonnesPerCubicMetre,
        #pragma warning restore CS1591
        [EnumMember(Value = "TonnesPerCubicCentimetre")]
        #pragma warning disable CS1591
        TonnesPerCubicCentimetre,
        #pragma warning restore CS1591
        [EnumMember(Value = "TonnesPerCubicMillimetre")]
        #pragma warning disable CS1591
        TonnesPerCubicMillimetre,
        #pragma warning restore CS1591
        [EnumMember(Value = "KilogramsPerCubicMetre")]
        #pragma warning disable CS1591
        KilogramsPerCubicMetre,
        #pragma warning restore CS1591
        [EnumMember(Value = "KilogramsPerCubicCentimetre")]
        #pragma warning disable CS1591
        KilogramsPerCubicCentimetre,
        #pragma warning restore CS1591
        [EnumMember(Value = "KilogramsPerCubicMillimetre")]
        #pragma warning disable CS1591
        KilogramsPerCubicMillimetre,
        #pragma warning restore CS1591
    }
}
