// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Result of a batch operation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MaterialBatchResult : IParsable
    {
        /// <summary>Errors from failed items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceGassApi.Models.BatchError>? Errors { get; set; }
#nullable restore
#else
        public List<global::SpaceGassApi.Models.BatchError> Errors { get; set; }
#endif
        /// <summary>Successfully processed items.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceGassApi.Models.Material>? Succeeded { get; set; }
#nullable restore
#else
        public List<global::SpaceGassApi.Models.Material> Succeeded { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.MaterialBatchResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.MaterialBatchResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.MaterialBatchResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::SpaceGassApi.Models.BatchError>(global::SpaceGassApi.Models.BatchError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "succeeded", n => { Succeeded = n.GetCollectionOfObjectValues<global::SpaceGassApi.Models.Material>(global::SpaceGassApi.Models.Material.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SpaceGassApi.Models.BatchError>("errors", Errors);
            writer.WriteCollectionOfObjectValues<global::SpaceGassApi.Models.Material>("succeeded", Succeeded);
        }
    }
}
#pragma warning restore CS0618
