// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Member element type. Determines the structural behavior of the member.Maps to SPACE GASS lookup table &quot;Member Type&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MemberType
    {
        [EnumMember(Value = "Normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "TensionOnly")]
        #pragma warning disable CS1591
        TensionOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "CompressionOnly")]
        #pragma warning disable CS1591
        CompressionOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cable")]
        #pragma warning disable CS1591
        Cable,
        #pragma warning restore CS1591
        [EnumMember(Value = "Gap")]
        #pragma warning disable CS1591
        Gap,
        #pragma warning restore CS1591
        [EnumMember(Value = "BrittleFuse")]
        #pragma warning disable CS1591
        BrittleFuse,
        #pragma warning restore CS1591
        [EnumMember(Value = "PlasticFuse")]
        #pragma warning disable CS1591
        PlasticFuse,
        #pragma warning restore CS1591
    }
}
