// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Optimization method for analysis.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OptimizationMethod
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "General")]
        #pragma warning disable CS1591
        General,
        #pragma warning restore CS1591
        [EnumMember(Value = "Linear")]
        #pragma warning disable CS1591
        Linear,
        #pragma warning restore CS1591
        [EnumMember(Value = "Circular")]
        #pragma warning disable CS1591
        Circular,
        #pragma warning restore CS1591
    }
}
