// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// DTO for reading a plate entity.Contains core plate properties without fixity data (handled separately if needed).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Plate : IParsable
    {
        /// <summary>Actual thickness of the plate. Unit: Section Properties (see GET /job/units).</summary>
        public double? ActualThickness { get; set; }
        /// <summary>Bending thickness of the plate. Unit: Section Properties (see GET /job/units).</summary>
        public double? BendingThickness { get; set; }
        /// <summary>Direction angle for plate orientation.</summary>
        public double? DirAngle { get; set; }
        /// <summary>Direction axis for member orientation.Maps to SPACE GASS lookup table &quot;Direction Axis&quot;.</summary>
        public global::SpaceGassApi.Models.DirectionAxis? DirAxis { get; set; }
        /// <summary>Direction node for plate orientation.</summary>
        public int? DirNode { get; set; }
        /// <summary>Optional GUID (hidden field in SPACEGASS)Some API users find this handy for tracking entities across systems</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; set; }
#nullable restore
#else
        public string Guid { get; set; }
#endif
        /// <summary>Primary key - must be unique, no duplicates allowed.Range: 1 to int.MaxValue</summary>
        public int? Key { get; set; }
        /// <summary>Material number assigned to this plate.</summary>
        public int? Material { get; set; }
        /// <summary>Membrane thickness of the plate. Unit: Section Properties (see GET /job/units).</summary>
        public double? MembraneThickness { get; set; }
        /// <summary>Node at corner A of the plate.</summary>
        public int? NodeA { get; set; }
        /// <summary>Node at corner B of the plate.</summary>
        public int? NodeB { get; set; }
        /// <summary>Node at corner C of the plate.</summary>
        public int? NodeC { get; set; }
        /// <summary>Node at corner D of the plate. 0 indicates a triangular (3-node) plate.</summary>
        public int? NodeD { get; set; }
        /// <summary>Plate offset. Unit: Length (see GET /job/units).</summary>
        public double? Offset { get; set; }
        /// <summary>Shear thickness of the plate. Unit: Section Properties (see GET /job/units).</summary>
        public double? ShearThickness { get; set; }
        /// <summary>Plate theory type for finite element analysis.Maps to SPACE GASS lookup table &quot;Plate Theory&quot;.</summary>
        public global::SpaceGassApi.Models.PlateTheory? Theory { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.Plate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.Plate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.Plate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actualThickness", n => { ActualThickness = n.GetDoubleValue(); } },
                { "bendingThickness", n => { BendingThickness = n.GetDoubleValue(); } },
                { "dirAngle", n => { DirAngle = n.GetDoubleValue(); } },
                { "dirAxis", n => { DirAxis = n.GetEnumValue<global::SpaceGassApi.Models.DirectionAxis>(); } },
                { "dirNode", n => { DirNode = n.GetIntValue(); } },
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "key", n => { Key = n.GetIntValue(); } },
                { "material", n => { Material = n.GetIntValue(); } },
                { "membraneThickness", n => { MembraneThickness = n.GetDoubleValue(); } },
                { "nodeA", n => { NodeA = n.GetIntValue(); } },
                { "nodeB", n => { NodeB = n.GetIntValue(); } },
                { "nodeC", n => { NodeC = n.GetIntValue(); } },
                { "nodeD", n => { NodeD = n.GetIntValue(); } },
                { "offset", n => { Offset = n.GetDoubleValue(); } },
                { "shearThickness", n => { ShearThickness = n.GetDoubleValue(); } },
                { "theory", n => { Theory = n.GetEnumValue<global::SpaceGassApi.Models.PlateTheory>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("actualThickness", ActualThickness);
            writer.WriteDoubleValue("bendingThickness", BendingThickness);
            writer.WriteDoubleValue("dirAngle", DirAngle);
            writer.WriteEnumValue<global::SpaceGassApi.Models.DirectionAxis>("dirAxis", DirAxis);
            writer.WriteIntValue("dirNode", DirNode);
            writer.WriteStringValue("guid", Guid);
            writer.WriteIntValue("key", Key);
            writer.WriteIntValue("material", Material);
            writer.WriteDoubleValue("membraneThickness", MembraneThickness);
            writer.WriteIntValue("nodeA", NodeA);
            writer.WriteIntValue("nodeB", NodeB);
            writer.WriteIntValue("nodeC", NodeC);
            writer.WriteIntValue("nodeD", NodeD);
            writer.WriteDoubleValue("offset", Offset);
            writer.WriteDoubleValue("shearThickness", ShearThickness);
            writer.WriteEnumValue<global::SpaceGassApi.Models.PlateTheory>("theory", Theory);
        }
    }
}
#pragma warning restore CS0618
