// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Plate element formulation type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PlateType
    {
        [EnumMember(Value = "BCPlates")]
        #pragma warning disable CS1591
        BCPlates,
        #pragma warning restore CS1591
        [EnumMember(Value = "DLPlates")]
        #pragma warning disable CS1591
        DLPlates,
        #pragma warning restore CS1591
    }
}
