// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// DTO for reading a self-weight load entity.Represents gravitational acceleration applied to the structure&apos;s own weight.Key: (Case) — one self-weight load per load case.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SelfWeightLoad : IParsable
    {
        /// <summary>Gravitational acceleration in the global X direction.</summary>
        public double? AccelerationX { get; set; }
        /// <summary>Gravitational acceleration in the global Y direction.</summary>
        public double? AccelerationY { get; set; }
        /// <summary>Gravitational acceleration in the global Z direction.</summary>
        public double? AccelerationZ { get; set; }
        /// <summary>The load case number this load belongs to.</summary>
        public int? Case { get; set; }
        /// <summary>Optional GUID (hidden field in SPACEGASS)Some API users find this handy for tracking entities across systems</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; set; }
#nullable restore
#else
        public string Guid { get; set; }
#endif
        /// <summary>Load category for grouping/organization.</summary>
        public int? LoadCategory { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.SelfWeightLoad"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.SelfWeightLoad CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.SelfWeightLoad();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accelerationX", n => { AccelerationX = n.GetDoubleValue(); } },
                { "accelerationY", n => { AccelerationY = n.GetDoubleValue(); } },
                { "accelerationZ", n => { AccelerationZ = n.GetDoubleValue(); } },
                { "case", n => { Case = n.GetIntValue(); } },
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "loadCategory", n => { LoadCategory = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("accelerationX", AccelerationX);
            writer.WriteDoubleValue("accelerationY", AccelerationY);
            writer.WriteDoubleValue("accelerationZ", AccelerationZ);
            writer.WriteIntValue("case", Case);
            writer.WriteStringValue("guid", Guid);
            writer.WriteIntValue("loadCategory", LoadCategory);
        }
    }
}
#pragma warning restore CS0618
