// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>
    /// Steel member design check summary result (FileId 209).The &quot;member&quot; field maps to the Group column in the datasheet.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SteelCheckSummary : IParsable
    {
        /// <summary>Load case ID of the critical case.</summary>
        public int? CriticalCase { get; set; }
        /// <summary>Failure mode description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Failure { get; set; }
#nullable restore
#else
        public string Failure { get; set; }
#endif
        /// <summary>Design check status flag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Flag { get; set; }
#nullable restore
#else
        public string Flag { get; set; }
#endif
        /// <summary>Design load factor (capacity ratio).</summary>
        public float? LoadFactor { get; set; }
        /// <summary>Member key (group key).</summary>
        public int? Member { get; set; }
        /// <summary>Section name used for the design check.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Section { get; set; }
#nullable restore
#else
        public string Section { get; set; }
#endif
        /// <summary>Critical segment length. Unit: Length (see GET /job/units).</summary>
        public float? SegmentLength { get; set; }
        /// <summary>Total member length. Unit: Length (see GET /job/units).</summary>
        public float? TotalLength { get; set; }
        /// <summary>Yield stress. Unit: Stress (see GET /job/units).</summary>
        public float? Yield { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.SteelCheckSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceGassApi.Models.SteelCheckSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceGassApi.Models.SteelCheckSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "criticalCase", n => { CriticalCase = n.GetIntValue(); } },
                { "failure", n => { Failure = n.GetStringValue(); } },
                { "flag", n => { Flag = n.GetStringValue(); } },
                { "loadFactor", n => { LoadFactor = n.GetFloatValue(); } },
                { "member", n => { Member = n.GetIntValue(); } },
                { "section", n => { Section = n.GetStringValue(); } },
                { "segmentLength", n => { SegmentLength = n.GetFloatValue(); } },
                { "totalLength", n => { TotalLength = n.GetFloatValue(); } },
                { "yield", n => { Yield = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("criticalCase", CriticalCase);
            writer.WriteStringValue("failure", Failure);
            writer.WriteStringValue("flag", Flag);
            writer.WriteFloatValue("loadFactor", LoadFactor);
            writer.WriteIntValue("member", Member);
            writer.WriteStringValue("section", Section);
            writer.WriteFloatValue("segmentLength", SegmentLength);
            writer.WriteFloatValue("totalLength", TotalLength);
            writer.WriteFloatValue("yield", Yield);
        }
    }
}
#pragma warning restore CS0618
