// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceGassApi.Models
{
    /// <summary>Temperature unit types (Field Index 4)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TemperatureUnit
    {
        [EnumMember(Value = "Fahrenheit")]
        #pragma warning disable CS1591
        Fahrenheit,
        #pragma warning restore CS1591
        [EnumMember(Value = "Celsius")]
        #pragma warning disable CS1591
        Celsius,
        #pragma warning restore CS1591
    }
}
