from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ...models.job import Job
    from ...models.problem_details import ProblemDetails

class DataRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /job/data
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new DataRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/job/data{?force*}", path_parameters)
    
    async def delete(self,request_configuration: Optional[RequestConfiguration[DataRequestBuilderDeleteQueryParameters]] = None) -> Optional[Job]:
        """
        Clears all model data while keeping current configuration (units, settings).Deletes ATS data files but preserves the job configuration.Returns the job object with zeroed model summary counts.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[Job]
        """
        request_info = self.to_delete_request_information(
            request_configuration
        )
        from ...models.problem_details import ProblemDetails

        error_mapping: dict[str, type[ParsableFactory]] = {
            "400": ProblemDetails,
            "401": ProblemDetails,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from ...models.job import Job

        return await self.request_adapter.send_async(request_info, Job, error_mapping)
    
    def to_delete_request_information(self,request_configuration: Optional[RequestConfiguration[DataRequestBuilderDeleteQueryParameters]] = None) -> RequestInformation:
        """
        Clears all model data while keeping current configuration (units, settings).Deletes ATS data files but preserves the job configuration.Returns the job object with zeroed model summary counts.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.DELETE, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> DataRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: DataRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return DataRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class DataRequestBuilderDeleteQueryParameters():
        """
        Clears all model data while keeping current configuration (units, settings).Deletes ATS data files but preserves the job configuration.Returns the job object with zeroed model summary counts.
        """
        # Must be true to confirm clearing. If false or omitted, operation is rejected for safety.
        force: Optional[bool] = None

    
    @dataclass
    class DataRequestBuilderDeleteRequestConfiguration(RequestConfiguration[DataRequestBuilderDeleteQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

