// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SpaceGassApi.Job.Import.TxtEscaped
{
    /// <summary>
    /// Builds and executes requests for operations under \job\import\txt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TxtRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TxtRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/import/txt{?merge*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TxtRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/import/txt{?merge*}", rawUrl)
        {
        }
        /// <summary>
        /// Imports a SpaceGass text file into the current job using the Fortran text import command.A job must be open before calling this endpoint.            The file should be uploaded as multipart/form-data with the field name &quot;file&quot;.            Example usage with curl:                curl -X POST &quot;/api/v1/job/import/txt?merge=false&quot; \      -F &quot;file=@/path/to/model.txt&quot;
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.JobStatus"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SpaceGassApi.Models.JobStatus?> PostAsync(MultipartBody body, Action<RequestConfiguration<global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder.TxtRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SpaceGassApi.Models.JobStatus> PostAsync(MultipartBody body, Action<RequestConfiguration<global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder.TxtRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SpaceGassApi.Models.JobStatus>(requestInfo, global::SpaceGassApi.Models.JobStatus.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Imports a SpaceGass text file into the current job using the Fortran text import command.A job must be open before calling this endpoint.            The file should be uploaded as multipart/form-data with the field name &quot;file&quot;.            Example usage with curl:                curl -X POST &quot;/api/v1/job/import/txt?merge=false&quot; \      -F &quot;file=@/path/to/model.txt&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder.TxtRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder.TxtRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Imports a SpaceGass text file into the current job using the Fortran text import command.A job must be open before calling this endpoint.            The file should be uploaded as multipart/form-data with the field name &quot;file&quot;.            Example usage with curl:                curl -X POST &quot;/api/v1/job/import/txt?merge=false&quot; \      -F &quot;file=@/path/to/model.txt&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TxtRequestBuilderPostQueryParameters 
        {
            /// <summary>If true, merges imported data with existing structure. If false (default), replaces existing data.</summary>
            [QueryParameter("merge")]
            public bool? Merge { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TxtRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder.TxtRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
