from enum import Enum

class EntityId(str, Enum):
    Nodes = "Nodes",
    Members = "Members",
    Plates = "Plates",
    PlateCuts = "PlateCuts",
    PlateStrips = "PlateStrips",
    Solids = "Solids",
    NodeLoads = "NodeLoads",
    MemberConcentratedLoads = "MemberConcentratedLoads",
    MemberDistributedLoads = "MemberDistributedLoads",
    MemberTorsionLoads = "MemberTorsionLoads",
    MemberPrestressLoads = "MemberPrestressLoads",
    PlateLoads = "PlateLoads",
    AreaLoads = "AreaLoads",
    PrescribedDisplacements = "PrescribedDisplacements",
    SelfWeightLoads = "SelfWeightLoads",
    ThermalLoads = "ThermalLoads",
    LumpedMassLoads = "LumpedMassLoads",
    Sections = "Sections",
    Materials = "Materials",
    Constraints = "Constraints",
    NodeRestraints = "NodeRestraints",
    MemberOffsets = "MemberOffsets",
    LoadCases = "LoadCases",
    LoadCaseGroups = "LoadCaseGroups",
    LoadCategories = "LoadCategories",
    CombinationLoadCases = "CombinationLoadCases",
    LoadCombinations = "LoadCombinations",
    AnalysisSettings = "AnalysisSettings",
    NodeResults = "NodeResults",
    MemberResults = "MemberResults",
    PlateResults = "PlateResults",

