// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Query.Analysis.Buckling;
using SpaceGassApi.Job.Query.Analysis.Dynamic;
using SpaceGassApi.Job.Query.Analysis.Static;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Query.Analysis
{
    /// <summary>
    /// Builds and executes requests for operations under \job\query\analysis
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnalysisRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The buckling property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Buckling.BucklingRequestBuilder Buckling
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Buckling.BucklingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dynamic property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Dynamic.DynamicRequestBuilder Dynamic
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Dynamic.DynamicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The static property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Static.StaticRequestBuilder Static
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Static.StaticRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.AnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalysisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.AnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalysisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
