from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.node import Node
    from .....models.problem_details import ProblemDetails

class ExistsRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /job/structure/nodes/exists
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ExistsRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/job/structure/nodes/exists{?tolerance*,x*,y*,z*}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[ExistsRequestBuilderGetQueryParameters]] = None) -> Optional[Node]:
        """
        Checks if a node exists within a given tolerance of the specified coordinates.Returns the first matching node found within the Euclidean distance tolerance.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[Node]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.problem_details import ProblemDetails

        error_mapping: dict[str, type[ParsableFactory]] = {
            "400": ProblemDetails,
            "404": ProblemDetails,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .....models.node import Node

        return await self.request_adapter.send_async(request_info, Node, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[ExistsRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        Checks if a node exists within a given tolerance of the specified coordinates.Returns the first matching node found within the Euclidean distance tolerance.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ExistsRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ExistsRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ExistsRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ExistsRequestBuilderGetQueryParameters():
        """
        Checks if a node exists within a given tolerance of the specified coordinates.Returns the first matching node found within the Euclidean distance tolerance.
        """
        # Maximum Euclidean distance to consider a match
        tolerance: Optional[float] = None

        # X coordinate to search near
        x: Optional[float] = None

        # Y coordinate to search near
        y: Optional[float] = None

        # Z coordinate to search near
        z: Optional[float] = None

    
    @dataclass
    class ExistsRequestBuilderGetRequestConfiguration(RequestConfiguration[ExistsRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

