// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Query.Design.SteelMember;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Query.Design
{
    /// <summary>
    /// Builds and executes requests for operations under \job\query\design
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The steelMember property</summary>
        public global::SpaceGassApi.Job.Query.Design.SteelMember.SteelMemberRequestBuilder SteelMember
        {
            get => new global::SpaceGassApi.Job.Query.Design.SteelMember.SteelMemberRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Design.DesignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesignRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/design", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Design.DesignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesignRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/design", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
