// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Query.Design.SteelMember.CheckSummary;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Query.Design.SteelMember
{
    /// <summary>
    /// Builds and executes requests for operations under \job\query\design\steel-member
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SteelMemberRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkSummary property</summary>
        public global::SpaceGassApi.Job.Query.Design.SteelMember.CheckSummary.CheckSummaryRequestBuilder CheckSummary
        {
            get => new global::SpaceGassApi.Job.Query.Design.SteelMember.CheckSummary.CheckSummaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Design.SteelMember.SteelMemberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SteelMemberRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/design/steel-member", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Design.SteelMember.SteelMemberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SteelMemberRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/design/steel-member", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
