<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceGassApi.Examples.Common\SpaceGassApi.Examples.Common.csproj" />
  </ItemGroup>

</Project>
