// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Import.TxtEscaped;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Import
{
    /// <summary>
    /// Builds and executes requests for operations under \job\import
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The txt property</summary>
        public global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder Txt
        {
            get => new global::SpaceGassApi.Job.Import.TxtEscaped.TxtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Import.ImportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/import", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Import.ImportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/import", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
