// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Structure.Sections.Bulk;
using SpaceGassApi.Job.Structure.Sections.Item;
using SpaceGassApi.Job.Structure.Sections.Metadata;
using SpaceGassApi.Job.Structure.Sections.Next;
using SpaceGassApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SpaceGassApi.Job.Structure.Sections
{
    /// <summary>
    /// Builds and executes requests for operations under \job\structure\sections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::SpaceGassApi.Job.Structure.Sections.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::SpaceGassApi.Job.Structure.Sections.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::SpaceGassApi.Job.Structure.Sections.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::SpaceGassApi.Job.Structure.Sections.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The next property</summary>
        public global::SpaceGassApi.Job.Structure.Sections.Next.NextRequestBuilder Next
        {
            get => new global::SpaceGassApi.Job.Structure.Sections.Next.NextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the SpaceGassApi.job.structure.sections.item collection</summary>
        /// <param name="position">The entity key</param>
        /// <returns>A <see cref="global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder"/></returns>
        public global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key", position);
                return new global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the SpaceGassApi.job.structure.sections.item collection</summary>
        /// <param name="position">The entity key</param>
        /// <returns>A <see cref="global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("key", position);
                return new global::SpaceGassApi.Job.Structure.Sections.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/structure/sections{?Limit*,Offset*,Sections*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/structure/sections{?Limit*,Offset*,Sections*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets all items with optional filtering and pagination.Results are always sorted by Key ascending.Pagination metadata is returned in response headers (Total-Count, Offset, Limit).
        /// </summary>
        /// <returns>A List&lt;global::SpaceGassApi.Models.Section&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::SpaceGassApi.Models.Section>?> GetAsync(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder.SectionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::SpaceGassApi.Models.Section>> GetAsync(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder.SectionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::SpaceGassApi.Models.Section>(requestInfo, global::SpaceGassApi.Models.Section.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates a new item. If a validator is registered, the item is validated before creation.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Models.Section"/></returns>
        /// <param name="body">DTO for creating a new user-defined section.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::SpaceGassApi.Models.ProblemDetails">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SpaceGassApi.Models.Section?> PostAsync(global::SpaceGassApi.Models.SectionCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SpaceGassApi.Models.Section> PostAsync(global::SpaceGassApi.Models.SectionCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::SpaceGassApi.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SpaceGassApi.Models.Section>(requestInfo, global::SpaceGassApi.Models.Section.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets all items with optional filtering and pagination.Results are always sorted by Key ascending.Pagination metadata is returned in response headers (Total-Count, Offset, Limit).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder.SectionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder.SectionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new item. If a validator is registered, the item is validated before creation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">DTO for creating a new user-defined section.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SpaceGassApi.Models.SectionCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SpaceGassApi.Models.SectionCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets all items with optional filtering and pagination.Results are always sorted by Key ascending.Pagination metadata is returned in response headers (Total-Count, Offset, Limit).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SectionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum number of items to return. Default is null (return all).</summary>
            public int? Limit { get; set; }
            /// <summary>Number of items to skip from the start of the result set. Default is 0.</summary>
            public int? Offset { get; set; }
            /// <summary>Comma-separated list of specific section numbers (e.g., &quot;1,5,10&quot;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Sections { get; set; }
#nullable restore
#else
            public string Sections { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SectionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SpaceGassApi.Job.Structure.Sections.SectionsRequestBuilder.SectionsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SectionsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
