// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceGassApi.Job.Query.Analysis.Static.Member;
using SpaceGassApi.Job.Query.Analysis.Static.Node;
using SpaceGassApi.Job.Query.Analysis.Static.Plate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceGassApi.Job.Query.Analysis.Static
{
    /// <summary>
    /// Builds and executes requests for operations under \job\query\analysis\static
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StaticRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The member property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Static.Member.MemberRequestBuilder Member
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Static.Member.MemberRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The node property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Static.Node.NodeRequestBuilder Node
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Static.Node.NodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plate property</summary>
        public global::SpaceGassApi.Job.Query.Analysis.Static.Plate.PlateRequestBuilder Plate
        {
            get => new global::SpaceGassApi.Job.Query.Analysis.Static.Plate.PlateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.Static.StaticRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaticRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis/static", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceGassApi.Job.Query.Analysis.Static.StaticRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StaticRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/job/query/analysis/static", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
